### ISSUE TITLE
Have a problem with running

### ISSUE THREAD

**Issue by wiouds** [WSUSeniorDesign/IAP_Generator#15]
![newmaster](https://cloud.githubusercontent.com/assets/16881770/14093721/08d4f5d2-f51e-11e5-8691-b256a18f5720.jpg)
Do you know what is causing this?

**Comment by jhennin** [comment]
Did you start up the mongo server?

-Jake

On Mar 28, 2016, at 7:49 PM, wiouds <notifications@github.com<mailto:notifications@github.com>> wrote:


[newmaster]<https://cloud.githubusercontent.com/assets/16881770/14093721/08d4f5d2-f51e-11e5-8691-b256a18f5720.jpg>
Do you know what is causing this?

-

**Comment by bergera** [comment]
Regarding `npm test` - there aren't currently any useful tests in the master branch. It's not really worth investigating at this point, there are a number of reasons why you might be seeing that error.

Regarding `npm start`, as @jhennin mentioned, it seems you don't have MongoDB running. See https://docs.mongodb.org/v3.0/tutorial/install-mongodb-on-windows/#run-mongodb.
