### ISSUE TITLE
NPM scripts don't run properly on Windows

### ISSUE THREAD

**Issue by bergera** [WSUSeniorDesign/IAP_Generator#2]
The scripts `start` and `debug` in `package.json` are written in a UNIX-only style, and don't execute properly on Windows. The NODE_PATH and NODE_ENV environment variables cannot be set this way.

```
17 error Windows_NT 10.0.10586
18 error argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error ceg-4981-team-projects@1.0.0 start: `NODE_PATH=./config:./app/controllers NODE_ENV=development ./node_modules/.bin/nodemon server.js`
22 error Exit status 1
23 error Failed at the ceg-4981-team-projects@1.0.0 start script 'NODE_PATH=./config:./app/controllers NODE_ENV=development ./node_modules/.bin/nodemon server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ceg-4981-team-projects package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_PATH=./config:./app/controllers NODE_ENV=development ./node_modules/.bin/nodemon server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ceg-4981-team-projects
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ceg-4981-team-projects
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bergera** [comment]
@kylewood07 If this is sort of error you were encountering, pull node-express-mongoose down again and give it another try. Remember to `git checkout node-express-mongoose` and `npm install` before you `npm start`.

**Comment by kylewood07** [comment]
Still having an issue with it. It's farther than it was so you fixed the environment variable issue. I'm now getting the errors shown below. It seems like my PC just won't use port 27017 for whatever Mongo wants to use it for. I've been looking all over for a fix for this and everything I'm finding has nothing to do with our setup or is "Restart node. duh" which isn't working. I'll keep digging and see if I can find anything.

![image](https://cloud.githubusercontent.com/assets/16820242/12970516/a7d7d5ae-d05d-11e5-8684-8f56213bfb15.png)

**Comment by bergera** [comment]
Is MongoDB running?
