### ISSUE TITLE
Should we add links for Requirements and Design docs to README?

### ISSUE THREAD

**Issue by bergera** [WSUSeniorDesign/IAP_Generator#7]

**Comment by bergera** [comment]
@MasterGeese @jhennin @kylewood07 @wiouds 

Any thoughts on this?

**Comment by jhennin** [comment]
I agree with Kyle, go for it.

-Jake

On Mar 10, 2016, at 2:59 PM, kylewood07 <notifications@github.com<mailto:notifications@github.com>> wrote:

Couldn't hurt. I don't think it's necessary but it might be nice to have.
On Mar 10, 2016 2:37 PM, "Andrew Berger" <notifications@github.com<mailto:notifications@github.com>> wrote:

> @MasterGeese <https://github.com/MasterGeese> @jhennin
> <https://github.com/jhennin> @kylewood07 <https://github.com/kylewood07>
> @wiouds <https://github.com/wiouds>
>
> Any thoughts on this?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/WSUSeniorDesign/IAP_Generator/issues/7#issuecomment-195013173>
> .
>

-

**Comment by bergera** [comment]
@jhennin Let's put documents in a new repo within the organization.

Could you either create a new repo called something like "documents" or give me sufficient permissions to create it?

**Comment by bergera** [comment]
We're all too lazy to do this.
